title: Felipe Gaiad
#author: Felipe Gaiad
email: fpgaiad@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
# social links
github_username:  github.com/fpgaiad
show_excerpts: true # set to false to remove excerpts on the homepage
