title: Felipe Gaiad
email: fpgaiad@gmail.com
theme: jekyll-theme-tactile
description: > # this means to ignore newlines until "baseurl:"
# social links
github_username: github.com/fpgaiad
show_excerpts: true # set to false to remove excerpts on the homepage
